In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "svg"
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset=pd.read_csv('Elevator_predictive_maintenance_with_missing_outliers.csv')

In [3]:
dataset

,Elevator_ID,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults,Maintenance_Required
0,E052,94.56,1.84,20.15,1470.3,57.15,2.91,3.09,70.42,83.0,2889.6,5.0,224.3,3.0,0.0
1,E093,105.00,4.27,20.10,1420.8,84.05,3.83,4.28,49.96,192.0,7276.7,13.0,602.8,7.0,1.0
2,E015,67.60,1.64,19.80,1471.1,46.36,2.23,2.96,80.75,31.0,1082.3,1.0,101.4,1.0,0.0
3,E072,105.00,4.24,13.63,1443.8,80.73,3.33,3.75,29.09,NaN,6716.5,12.0,575.6,9.0,1.0
4,E061,92.52,2.13,18.64,1466.5,62.52,3.11,3.06,56.64,105.0,3116.7,4.0,281.1,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,E064,75.25,2.01,18.61,1488.1,44.03,2.26,2.65,72.45,36.0,1156.6,2.0,76.5,1.0,0.0
495,E063,99.81,2.98,16.39,1456.0,54.79,3.34,2.72,74.99,40.0,2621.0,7.0,173.2,2.0,0.0
496,E069,99.31,2.66,19.45,1443.8,NaN,2.67,2.94,47.38,76.0,3639.4,4.0,256.4,2.0,0.0
497,E022,85.15,2.41,14.90,1470.0,56.17,2.73,2.83,40.67,41.0,2693.9,8.0,218.3,4.0,0.0
498,E093,86.66,1.46,15.64,1479.8,58.78,3.28,3.26,55.87,67.0,2991.5,4.0,256.7,2.0,0.0

In [4]:
dataset=dataset.drop(columns=['Elevator_ID'])

In [5]:
output=dataset['Maintenance_Required'].copy()
dataset=dataset.drop(columns=['Maintenance_Required'])

In [6]:
dataset

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
0,94.56,1.84,20.15,1470.3,57.15,2.91,3.09,70.42,83.0,2889.6,5.0,224.3,3.0
1,105.00,4.27,20.10,1420.8,84.05,3.83,4.28,49.96,192.0,7276.7,13.0,602.8,7.0
2,67.60,1.64,19.80,1471.1,46.36,2.23,2.96,80.75,31.0,1082.3,1.0,101.4,1.0
3,105.00,4.24,13.63,1443.8,80.73,3.33,3.75,29.09,NaN,6716.5,12.0,575.6,9.0
4,92.52,2.13,18.64,1466.5,62.52,3.11,3.06,56.64,105.0,3116.7,4.0,281.1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,75.25,2.01,18.61,1488.1,44.03,2.26,2.65,72.45,36.0,1156.6,2.0,76.5,1.0
495,99.81,2.98,16.39,1456.0,54.79,3.34,2.72,74.99,40.0,2621.0,7.0,173.2,2.0
496,99.31,2.66,19.45,1443.8,NaN,2.67,2.94,47.38,76.0,3639.4,4.0,256.4,2.0
497,85.15,2.41,14.90,1470.0,56.17,2.73,2.83,40.67,41.0,2693.9,8.0,218.3,4.0
498,86.66,1.46,15.64,1479.8,58.78,3.28,3.26,55.87,67.0,2991.5,4.0,256.7,2.0

In [7]:
dataset.isnull().sum()

Motor_Temperature_C       14
Motor_Vibration_mm_s      13
Motor_Current_A           17
Motor_Speed_RPM           18
Brake_Temperature_C       11
Door_Opening_Time_s        8
Door_Closing_Time_s       11
Load_Percentage           13
Number_of_Trips           18
Operating_Hours           24
Error_Count               15
Days_Since_Maintenance    18
Previous_Faults           15
dtype: int64

In [8]:
dataset.dtypes

Motor_Temperature_C       float64
Motor_Vibration_mm_s      float64
Motor_Current_A           float64
Motor_Speed_RPM           float64
Brake_Temperature_C       float64
Door_Opening_Time_s       float64
Door_Closing_Time_s       float64
Load_Percentage           float64
Number_of_Trips           float64
Operating_Hours           float64
Error_Count               float64
Days_Since_Maintenance    float64
Previous_Faults           float64
dtype: object

In [9]:
for columnName in dataset.columns:
     print(columnName)

Motor_Temperature_C
Motor_Vibration_mm_s
Motor_Current_A
Motor_Speed_RPM
Brake_Temperature_C
Door_Opening_Time_s
Door_Closing_Time_s
Load_Percentage
Number_of_Trips
Operating_Hours
Error_Count
Days_Since_Maintenance
Previous_Faults

# Central tendancy

In [10]:
dataset

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
0,94.56,1.84,20.15,1470.3,57.15,2.91,3.09,70.42,83.0,2889.6,5.0,224.3,3.0
1,105.00,4.27,20.10,1420.8,84.05,3.83,4.28,49.96,192.0,7276.7,13.0,602.8,7.0
2,67.60,1.64,19.80,1471.1,46.36,2.23,2.96,80.75,31.0,1082.3,1.0,101.4,1.0
3,105.00,4.24,13.63,1443.8,80.73,3.33,3.75,29.09,NaN,6716.5,12.0,575.6,9.0
4,92.52,2.13,18.64,1466.5,62.52,3.11,3.06,56.64,105.0,3116.7,4.0,281.1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,75.25,2.01,18.61,1488.1,44.03,2.26,2.65,72.45,36.0,1156.6,2.0,76.5,1.0
495,99.81,2.98,16.39,1456.0,54.79,3.34,2.72,74.99,40.0,2621.0,7.0,173.2,2.0
496,99.31,2.66,19.45,1443.8,NaN,2.67,2.94,47.38,76.0,3639.4,4.0,256.4,2.0
497,85.15,2.41,14.90,1470.0,56.17,2.73,2.83,40.67,41.0,2693.9,8.0,218.3,4.0
498,86.66,1.46,15.64,1479.8,58.78,3.28,3.26,55.87,67.0,2991.5,4.0,256.7,2.0

In [11]:
dataset[["Motor_Temperature_C"]].mean()

Motor_Temperature_C    95.212
dtype: float64

In [12]:
dataset[["Motor_Temperature_C"]].median()

Motor_Temperature_C    105.0
dtype: float64

In [13]:
dataset[["Motor_Temperature_C"]].mode()

   Motor_Temperature_C
0                105.0

In [14]:
dataset.describe()

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
count,485.000000,486.000000,482.000000,481.000000,488.000000,491.000000,488.000000,486.000000,481.000000,475.000000,484.000000,481.000000,484.000000
mean,95.212000,2.797963,17.646955,1455.618004,65.636737,3.108941,3.386967,61.359347,111.492723,4436.381053,5.555785,368.235135,3.727273
std,14.474221,1.081327,2.505355,26.671646,13.452489,0.553273,0.594451,18.735801,62.731301,2183.102955,3.625592,186.896500,2.391972
min,45.640000,-1.515000,8.203750,1246.470000,2.991250,0.745000,0.700000,-16.991250,-155.500000,-5629.900000,-9.500000,-507.950000,-5.500000
25%,88.050000,2.072500,16.135000,1439.200000,55.697500,2.775000,2.960000,47.927500,67.000000,2798.600000,3.000000,225.300000,2.000000
50%,105.000000,2.820000,17.795000,1454.700000,66.550000,3.140000,3.400000,61.500000,104.000000,4499.400000,5.000000,375.600000,4.000000
75%,105.000000,3.510000,19.310000,1471.900000,76.780000,3.470000,3.800000,73.982500,156.000000,6187.900000,8.000000,520.800000,5.000000
max,147.400000,7.095000,27.238750,1667.990000,129.486250,5.505000,6.060000,138.813750,378.500000,14598.500000,20.500000,1251.850000,12.500000

In [15]:
descriptive=pd.DataFrame()

In [16]:
descriptive

Empty DataFrame
Columns: []
Index: []

In [17]:
describe=pd.DataFrame(index=["mean","median","mode"],columns=dataset.columns)

In [18]:
describe

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
for columnName in dataset.columns:
    describe.loc["mean", columnName] = dataset[columnName].mean()
    describe.loc["median", columnName] = dataset[columnName].median()
    describe.loc["mode", columnName] = dataset[columnName].mode().iloc[0]

In [20]:
describe

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
mean,95.212,2.797963,17.646955,1455.618004,65.636737,3.108941,3.386967,61.359347,111.492723,4436.381053,5.555785,368.235135,3.727273
median,105.0,2.82,17.795,1454.7,66.55,3.14,3.4,61.5,104.0,4499.4,5.0,375.6,4.0
mode,105.0,2.18,16.25,1451.7,85.0,2.86,3.6,100.0,95.0,-5629.9,6.0,0.0,5.0

# Percentile

In [21]:
np.nanpercentile(dataset["Motor_Temperature_C"],75)

np.float64(105.0)

In [22]:
descriptive=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","99","Q4:100%"],columns=dataset.columns)
for columnName in dataset:
    descriptive.loc["mean",columnName]=dataset[columnName].mean()
    descriptive.loc["median",columnName]=dataset[columnName].median()
    descriptive.loc["mode",columnName]=dataset[columnName].mode()[0]
    descriptive.loc["Q1:25%",columnName]=dataset.describe()[columnName]["25%"]
    descriptive.loc["Q2:50%",columnName]=dataset.describe()[columnName]["50%"]
    descriptive.loc["Q3:75%",columnName]=dataset.describe()[columnName]["75%"]
    descriptive.loc["99",columnName]=np.nanpercentile(dataset[columnName],99)
    descriptive.loc["Q4:100%",columnName]=dataset.describe()[columnName]["max"]

descriptive

# outliers

In [23]:
descriptive=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","99","Q4:100%","IQR","1.5RULE","LESSER","GREATER","min","max"],columns=dataset.columns)
for columnName in dataset:
    descriptive.loc["mean",columnName]=dataset[columnName].mean()
    descriptive.loc["median",columnName]=dataset[columnName].median()
    descriptive.loc["mode",columnName]=dataset[columnName].mode()[0]
    descriptive.loc["Q1:25%",columnName]=dataset.describe()[columnName]["25%"]
    descriptive.loc["Q2:50%",columnName]=dataset.describe()[columnName]["50%"]
    descriptive.loc["Q3:75%",columnName]=dataset.describe()[columnName]["75%"]
    descriptive.loc["99",columnName]=np.nanpercentile(dataset[columnName],99)
    descriptive.loc["Q4:100%",columnName]=dataset.describe()[columnName]["max"]
    descriptive.loc["IQR",columnName]=descriptive.loc["Q3:75%",columnName]- descriptive.loc["Q1:25%",columnName]
    descriptive.loc["1.5RULE",columnName]=1.5* descriptive.loc["IQR",columnName]
    descriptive.loc["LESSER",columnName]=descriptive.loc["Q1:25%",columnName]- descriptive.loc["1.5RULE",columnName]
    descriptive.loc["GREATER",columnName]=descriptive.loc["Q3:75%",columnName]+ descriptive.loc["1.5RULE",columnName]
    descriptive.loc["min",columnName]=dataset[columnName].min()
    descriptive.loc["max",columnName]=dataset[columnName].max()

In [24]:
descriptive

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
mean,95.212,2.797963,17.646955,1455.618004,65.636737,3.108941,3.386967,61.359347,111.492723,4436.381053,5.555785,368.235135,3.727273
median,105.0,2.82,17.795,1454.7,66.55,3.14,3.4,61.5,104.0,4499.4,5.0,375.6,4.0
mode,105.0,2.18,16.25,1451.7,85.0,2.86,3.6,100.0,95.0,-5629.9,6.0,0.0,5.0
Q1:25%,88.05,2.0725,16.135,1439.2,55.6975,2.775,2.96,47.9275,67.0,2798.6,3.0,225.3,2.0
Q2:50%,105.0,2.82,17.795,1454.7,66.55,3.14,3.4,61.5,104.0,4499.4,5.0,375.6,4.0
Q3:75%,105.0,3.51,19.31,1471.9,76.78,3.47,3.8,73.9825,156.0,6187.9,8.0,520.8,5.0
99,105.0,5.0225,22.9936,1510.6,85.0,4.224,4.5413,100.0,261.6,7903.984,14.17,683.12,10.0
Q4:100%,147.4,7.095,27.23875,1667.99,129.48625,5.505,6.06,138.81375,378.5,14598.5,20.5,1251.85,12.5
IQR,16.95,1.4375,3.175,32.7,21.0825,0.695,0.84,26.055,89.0,3389.3,5.0,295.5,3.0
1.5RULE,25.425,2.15625,4.7625,49.05,31.62375,1.0425,1.26,39.0825,133.5,5083.95,7.5,443.25,4.5
LESSER,62.625,-0.08375,11.3725,1390.15,24.07375,1.7325,1.7,8.845,-66.5,-2285.35,-4.5,-217.95,-2.5
GREATER,130.425,5.66625,24.0725,1520.95,108.40375,4.5125,5.06,113.065,289.5,11271.85,15.5,964.05,9.5
min,45.64,-1.515,8.20375,1246.47,2.99125,0.745,0.7,-16.99125,-155.5,-5629.9,-9.5,-507.95,-5.5
max,147.4,7.095,27.23875,1667.99,129.48625,5.505,6.06,138.81375,378.5,14598.5,20.5,1251.85,12.5

In [25]:
descriptive["Motor_Temperature_C"]["LESSER"]>descriptive["Motor_Temperature_C"]["min"]

np.True_

In [26]:
lesser=[]
greater=[]

for columnName in dataset:
    if(descriptive[columnName]["min"]<descriptive[columnName]["LESSER"]):
       lesser.append(columnName)
    if(descriptive[columnName]["max"]>descriptive[columnName]["GREATER"]):
       greater.append(columnName)

In [27]:
lesser

['Motor_Temperature_C',
 'Motor_Vibration_mm_s',
 'Motor_Current_A',
 'Motor_Speed_RPM',
 'Brake_Temperature_C',
 'Door_Opening_Time_s',
 'Door_Closing_Time_s',
 'Load_Percentage',
 'Number_of_Trips',
 'Operating_Hours',
 'Error_Count',
 'Days_Since_Maintenance',
 'Previous_Faults']

In [28]:
greater

['Motor_Temperature_C',
 'Motor_Vibration_mm_s',
 'Motor_Current_A',
 'Motor_Speed_RPM',
 'Brake_Temperature_C',
 'Door_Opening_Time_s',
 'Door_Closing_Time_s',
 'Load_Percentage',
 'Number_of_Trips',
 'Operating_Hours',
 'Error_Count',
 'Days_Since_Maintenance',
 'Previous_Faults']

In [29]:
for columnName in lesser:
    dataset.loc[dataset[columnName] < descriptive[columnName]["LESSER"], columnName] = descriptive[columnName]["LESSER"]
    descriptive[columnName]["min"] = dataset[columnName].min()

for columnName in greater:
    dataset.loc[dataset[columnName] > descriptive[columnName]["GREATER"], columnName] = descriptive[columnName]["GREATER"]
    descriptive[columnName]["max"] = dataset[columnName].max()

In [30]:
descriptive=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","99","Q4:100%","IQR","1.5RULE","LESSER","GREATER","min","max"],columns=dataset.columns)
for columnName in dataset:
    descriptive.loc["mean",columnName]=dataset[columnName].mean()
    descriptive.loc["median",columnName]=dataset[columnName].median()
    descriptive.loc["mode",columnName]=dataset[columnName].mode()[0]
    descriptive.loc["Q1:25%",columnName]=dataset.describe()[columnName]["25%"]
    descriptive.loc["Q2:50%",columnName]=dataset.describe()[columnName]["50%"]
    descriptive.loc["Q3:75%",columnName]=dataset.describe()[columnName]["75%"]
    descriptive.loc["99",columnName]=np.nanpercentile(dataset[columnName],99)
    descriptive.loc["Q4:100%",columnName]=dataset.describe()[columnName]["max"]
    descriptive.loc["IQR",columnName]=descriptive.loc["Q3:75%",columnName]- descriptive.loc["Q1:25%",columnName]
    descriptive.loc["1.5RULE",columnName]=1.5* descriptive.loc["IQR",columnName]
    descriptive.loc["LESSER",columnName]=descriptive.loc["Q1:25%",columnName]- descriptive.loc["1.5RULE",columnName]
    descriptive.loc["GREATER",columnName]=descriptive.loc["Q3:75%",columnName]+ descriptive.loc["1.5RULE",columnName]
    descriptive.loc["min",columnName]=dataset[columnName].min()
    descriptive.loc["max",columnName]=dataset[columnName].max()

In [31]:
descriptive

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
mean,95.355866,2.797968,17.652147,1455.611019,65.636737,3.109333,3.386967,61.359527,111.492723,4436.418737,5.544421,368.239709,3.722107
median,105.0,2.82,17.795,1454.7,66.55,3.14,3.4,61.5,104.0,4499.4,5.0,375.6,4.0
mode,105.0,2.18,11.3725,1451.7,85.0,2.86,3.6,100.0,95.0,-2285.35,6.0,0.0,5.0
Q1:25%,88.05,2.0725,16.135,1439.2,55.6975,2.775,2.96,47.9275,67.0,2798.6,3.0,225.3,2.0
Q2:50%,105.0,2.82,17.795,1454.7,66.55,3.14,3.4,61.5,104.0,4499.4,5.0,375.6,4.0
Q3:75%,105.0,3.51,19.31,1471.9,76.78,3.47,3.8,73.9825,156.0,6187.9,8.0,520.8,5.0
99,105.0,5.0225,22.9936,1510.6,85.0,4.224,4.5413,100.0,261.6,7903.984,14.17,683.12,9.5
Q4:100%,130.425,5.66625,24.0725,1520.95,108.40375,4.5125,5.06,113.065,289.5,11271.85,15.5,964.05,9.5
IQR,16.95,1.4375,3.175,32.7,21.0825,0.695,0.84,26.055,89.0,3389.3,5.0,295.5,3.0
1.5RULE,25.425,2.15625,4.7625,49.05,31.62375,1.0425,1.26,39.0825,133.5,5083.95,7.5,443.25,4.5
LESSER,62.625,-0.08375,11.3725,1390.15,24.07375,1.7325,1.7,8.845,-66.5,-2285.35,-4.5,-217.95,-2.5
GREATER,130.425,5.66625,24.0725,1520.95,108.40375,4.5125,5.06,113.065,289.5,11271.85,15.5,964.05,9.5
min,62.625,-0.08375,11.3725,1390.15,24.07375,1.7325,1.7,8.845,-66.5,-2285.35,-4.5,-217.95,-2.5
max,130.425,5.66625,24.0725,1520.95,108.40375,4.5125,5.06,113.065,289.5,11271.85,15.5,964.05,9.5

In [32]:
lesser=[]
greater=[]

for columnName in dataset:
    if(descriptive[columnName]["min"]<descriptive[columnName]["LESSER"]):
       lesser.append(columnName)
    if(descriptive[columnName]["max"]>descriptive[columnName]["GREATER"]):
       greater.append(columnName)

In [33]:
lesser

[]

In [34]:
greater

[]

# frequency

In [35]:
dataset["Motor_Temperature_C"].value_counts()

Motor_Temperature_C
105.000    261
62.625      20
76.970       2
93.790       2
92.150       2
          ...
75.250       1
99.810       1
99.310       1
85.150       1
86.660       1
Name: count, Length: 203, dtype: int64

In [36]:
freqtable=pd.DataFrame(columns=["unique_value","freq","relative_freq","cumsum"])

In [37]:
freqtable

Empty DataFrame
Columns: [unique_value, freq, relative_freq, cumsum]
Index: []

In [38]:
freqtable["unique_value"]=dataset["Motor_Temperature_C"].value_counts().index
freqtable["freq"]=dataset["Motor_Temperature_C"].value_counts().values
freqtable["relative_freq"]=(freqtable["freq"]/133)
freqtable["cumsum"]=freqtable["relative_freq"].cumsum()

In [39]:
def freqtable(columnName,dataset):
    freqtable=pd.DataFrame(columns=["unique_value","freq","relative_freq","cumsum"])
    freqtable["unique_value"]=dataset[columnName].value_counts().index
    freqtable["freq"]=dataset[columnName].value_counts().values
    freqtable["relative_freq"]=(freqtable["freq"]/133)
    freqtable["cumsum"]=freqtable["relative_freq"].cumsum()
    return freqtable

In [40]:
freqtable("Motor_Vibration_mm_s",dataset)

     unique_value  freq  relative_freq    cumsum
0            2.18     6       0.045113  0.045113
1            1.99     5       0.037594  0.082707
2            3.31     5       0.037594  0.120301
3            2.57     5       0.037594  0.157895
4            3.43     5       0.037594  0.195489
..            ...   ...            ...       ...
283          1.17     1       0.007519  3.624060
284          2.52     1       0.007519  3.631579
285          1.30     1       0.007519  3.639098
286          1.91     1       0.007519  3.646617
287          2.41     1       0.007519  3.654135

[288 rows x 4 columns]

In [41]:
def Univariate(dataset):
     descriptive=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","99","Q4:100%","IQR","1.5RULE","LESSER","GREATER","min","max","skew","kurtosis"],columns=dataset.columns)
     for columnName in dataset:
        descriptive.loc["mean",columnName]=dataset[columnName].mean()
        descriptive.loc["median",columnName]=dataset[columnName].median()
        descriptive.loc["mode",columnName]=dataset[columnName].mode()[0]
        descriptive.loc["Q1:25%",columnName]=dataset.describe()[columnName]["25%"]
        descriptive.loc["Q2:50%",columnName]=dataset.describe()[columnName]["50%"]
        descriptive.loc["Q3:75%",columnName]=dataset.describe()[columnName]["75%"]
        descriptive.loc["99",columnName]=np.nanpercentile(dataset[columnName],99)
        descriptive.loc["Q4:100%",columnName]=dataset.describe()[columnName]["max"]
        descriptive.loc["IQR",columnName]=descriptive.loc["Q3:75%",columnName]- descriptive.loc["Q1:25%",columnName]
        descriptive.loc["1.5RULE",columnName]=1.5* descriptive.loc["IQR",columnName]
        descriptive.loc["LESSER",columnName]=descriptive.loc["Q1:25%",columnName]- descriptive.loc["1.5RULE",columnName]
        descriptive.loc["GREATER",columnName]=descriptive.loc["Q3:75%",columnName]+ descriptive.loc["1.5RULE",columnName]
        descriptive.loc["min",columnName]=dataset[columnName].min()
        descriptive.loc["max",columnName]=dataset[columnName].max()
        descriptive.loc["skew",columnName]=dataset[columnName].skew()
        descriptive.loc["kurtosis",columnName]=dataset[columnName].kurtosis()
         
     return descriptive

In [42]:
Univariate(dataset)

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
mean,95.355866,2.797968,17.652147,1455.611019,65.636737,3.109333,3.386967,61.359527,111.492723,4436.418737,5.544421,368.239709,3.722107
median,105.0,2.82,17.795,1454.7,66.55,3.14,3.4,61.5,104.0,4499.4,5.0,375.6,4.0
mode,105.0,2.18,11.3725,1451.7,85.0,2.86,3.6,100.0,95.0,-2285.35,6.0,0.0,5.0
Q1:25%,88.05,2.0725,16.135,1439.2,55.6975,2.775,2.96,47.9275,67.0,2798.6,3.0,225.3,2.0
Q2:50%,105.0,2.82,17.795,1454.7,66.55,3.14,3.4,61.5,104.0,4499.4,5.0,375.6,4.0
Q3:75%,105.0,3.51,19.31,1471.9,76.78,3.47,3.8,73.9825,156.0,6187.9,8.0,520.8,5.0
99,105.0,5.0225,22.9936,1510.6,85.0,4.224,4.5413,100.0,261.6,7903.984,14.17,683.12,9.5
Q4:100%,130.425,5.66625,24.0725,1520.95,108.40375,4.5125,5.06,113.065,289.5,11271.85,15.5,964.05,9.5
IQR,16.95,1.4375,3.175,32.7,21.0825,0.695,0.84,26.055,89.0,3389.3,5.0,295.5,3.0
1.5RULE,25.425,2.15625,4.7625,49.05,31.62375,1.0425,1.26,39.0825,133.5,5083.95,7.5,443.25,4.5
LESSER,62.625,-0.08375,11.3725,1390.15,24.07375,1.7325,1.7,8.845,-66.5,-2285.35,-4.5,-217.95,-2.5
GREATER,130.425,5.66625,24.0725,1520.95,108.40375,4.5125,5.06,113.065,289.5,11271.85,15.5,964.05,9.5
min,62.625,-0.08375,11.3725,1390.15,24.07375,1.7325,1.7,8.845,-66.5,-2285.35,-4.5,-217.95,-2.5
max,130.425,5.66625,24.0725,1520.95,108.40375,4.5125,5.06,113.065,289.5,11271.85,15.5,964.05,9.5
skew,-1.145851,-0.096269,-0.202879,0.190546,-0.272511,-0.156719,-0.057845,-0.077323,0.334258,-0.125831,0.353778,-0.100683,0.138143
kurtosis,0.027515,-0.36191,-0.04505,-0.234062,-0.613843,-0.307519,-0.471371,-0.241708,-0.434944,-0.783142,-0.180769,-0.706012,-0.508777

# skew

#The negative skewness indicates that the data is slightly left-skewed, with more observations concentrated toward the higher values and a longer tail toward the lower values.”

# kurtosis

A dataset with a kurtosis less than 3 is called a platykurtic distribution.fair distribution

In [43]:
dataset.isnull().sum()

Motor_Temperature_C       14
Motor_Vibration_mm_s      13
Motor_Current_A           17
Motor_Speed_RPM           18
Brake_Temperature_C       11
Door_Opening_Time_s        8
Door_Closing_Time_s       11
Load_Percentage           13
Number_of_Trips           18
Operating_Hours           24
Error_Count               15
Days_Since_Maintenance    18
Previous_Faults           15
dtype: int64

# input columns → mean/median/mode can be used depending on the variable.
Maintenance_Required output → preferably remove missing target rows or obtain the correct label.

In [44]:
dataset.isnull().sum()

Motor_Temperature_C       14
Motor_Vibration_mm_s      13
Motor_Current_A           17
Motor_Speed_RPM           18
Brake_Temperature_C       11
Door_Opening_Time_s        8
Door_Closing_Time_s       11
Load_Percentage           13
Number_of_Trips           18
Operating_Hours           24
Error_Count               15
Days_Since_Maintenance    18
Previous_Faults           15
dtype: int64

In [45]:
dataset

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
0,94.56,1.84,20.15,1470.3,57.15,2.91,3.09,70.42,83.0,2889.6,5.0,224.3,3.0
1,105.00,4.27,20.10,1420.8,84.05,3.83,4.28,49.96,192.0,7276.7,13.0,602.8,7.0
2,67.60,1.64,19.80,1471.1,46.36,2.23,2.96,80.75,31.0,1082.3,1.0,101.4,1.0
3,105.00,4.24,13.63,1443.8,80.73,3.33,3.75,29.09,NaN,6716.5,12.0,575.6,9.0
4,92.52,2.13,18.64,1466.5,62.52,3.11,3.06,56.64,105.0,3116.7,4.0,281.1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,75.25,2.01,18.61,1488.1,44.03,2.26,2.65,72.45,36.0,1156.6,2.0,76.5,1.0
495,99.81,2.98,16.39,1456.0,54.79,3.34,2.72,74.99,40.0,2621.0,7.0,173.2,2.0
496,99.31,2.66,19.45,1443.8,NaN,2.67,2.94,47.38,76.0,3639.4,4.0,256.4,2.0
497,85.15,2.41,14.90,1470.0,56.17,2.73,2.83,40.67,41.0,2693.9,8.0,218.3,4.0
498,86.66,1.46,15.64,1479.8,58.78,3.28,3.26,55.87,67.0,2991.5,4.0,256.7,2.0

In [46]:
dataset.isnull().sum()

Motor_Temperature_C       14
Motor_Vibration_mm_s      13
Motor_Current_A           17
Motor_Speed_RPM           18
Brake_Temperature_C       11
Door_Opening_Time_s        8
Door_Closing_Time_s       11
Load_Percentage           13
Number_of_Trips           18
Operating_Hours           24
Error_Count               15
Days_Since_Maintenance    18
Previous_Faults           15
dtype: int64

In [47]:
import numpy as np
from sklearn.impute import SimpleImputer
columns=dataset.columns
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(dataset)
df=imp.transform(dataset)

In [48]:
df

array([[ 94.56,   1.84,  20.15, ...,   5.  , 224.3 ,   3.  ],
       [105.  ,   4.27,  20.1 , ...,  13.  , 602.8 ,   7.  ],
       [ 67.6 ,   1.64,  19.8 , ...,   1.  , 101.4 ,   1.  ],
       ...,
       [ 99.31,   2.66,  19.45, ...,   4.  , 256.4 ,   2.  ],
       [ 85.15,   2.41,  14.9 , ...,   8.  , 218.3 ,   4.  ],
       [ 86.66,   1.46,  15.64, ...,   4.  , 256.7 ,   2.  ]],
      shape=(499, 13))

In [49]:
dataset=pd.DataFrame(df,columns=dataset.columns)

In [50]:
dataset

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
0,94.56,1.84,20.15,1470.3,57.150000,2.91,3.09,70.42,83.000000,2889.6,5.0,224.3,3.0
1,105.00,4.27,20.10,1420.8,84.050000,3.83,4.28,49.96,192.000000,7276.7,13.0,602.8,7.0
2,67.60,1.64,19.80,1471.1,46.360000,2.23,2.96,80.75,31.000000,1082.3,1.0,101.4,1.0
3,105.00,4.24,13.63,1443.8,80.730000,3.33,3.75,29.09,111.492723,6716.5,12.0,575.6,9.0
4,92.52,2.13,18.64,1466.5,62.520000,3.11,3.06,56.64,105.000000,3116.7,4.0,281.1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,75.25,2.01,18.61,1488.1,44.030000,2.26,2.65,72.45,36.000000,1156.6,2.0,76.5,1.0
495,99.81,2.98,16.39,1456.0,54.790000,3.34,2.72,74.99,40.000000,2621.0,7.0,173.2,2.0
496,99.31,2.66,19.45,1443.8,65.636737,2.67,2.94,47.38,76.000000,3639.4,4.0,256.4,2.0
497,85.15,2.41,14.90,1470.0,56.170000,2.73,2.83,40.67,41.000000,2693.9,8.0,218.3,4.0
498,86.66,1.46,15.64,1479.8,58.780000,3.28,3.26,55.87,67.000000,2991.5,4.0,256.7,2.0

In [51]:
dataset.isnull().sum()

Motor_Temperature_C       0
Motor_Vibration_mm_s      0
Motor_Current_A           0
Motor_Speed_RPM           0
Brake_Temperature_C       0
Door_Opening_Time_s       0
Door_Closing_Time_s       0
Load_Percentage           0
Number_of_Trips           0
Operating_Hours           0
Error_Count               0
Days_Since_Maintenance    0
Previous_Faults           0
dtype: int64

# Std & Varriance

In [53]:
def Univariate(dataset):
     descriptive=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","99","Q4:100%","IQR","1.5RULE","LESSER","GREATER","min","max","skew","kurtosis","var","std"],columns=dataset.columns)
     for columnName in dataset:
        descriptive.loc["mean",columnName]=dataset[columnName].mean()
        descriptive.loc["median",columnName]=dataset[columnName].median()
        descriptive.loc["mode",columnName]=dataset[columnName].mode()[0]
        descriptive.loc["Q1:25%",columnName]=dataset.describe()[columnName]["25%"]
        descriptive.loc["Q2:50%",columnName]=dataset.describe()[columnName]["50%"]
        descriptive.loc["Q3:75%",columnName]=dataset.describe()[columnName]["75%"]
        descriptive.loc["99",columnName]=np.nanpercentile(dataset[columnName],99)
        descriptive.loc["Q4:100%",columnName]=dataset.describe()[columnName]["max"]
        descriptive.loc["IQR",columnName]=descriptive.loc["Q3:75%",columnName]- descriptive.loc["Q1:25%",columnName]
        descriptive.loc["1.5RULE",columnName]=1.5* descriptive.loc["IQR",columnName]
        descriptive.loc["LESSER",columnName]=descriptive.loc["Q1:25%",columnName]- descriptive.loc["1.5RULE",columnName]
        descriptive.loc["GREATER",columnName]=descriptive.loc["Q3:75%",columnName]+ descriptive.loc["1.5RULE",columnName]
        descriptive.loc["min",columnName]=dataset[columnName].min()
        descriptive.loc["max",columnName]=dataset[columnName].max()
        descriptive.loc["skew",columnName]=dataset[columnName].skew()
        descriptive.loc["kurtosis",columnName]=dataset[columnName].kurtosis()
        descriptive.loc["var",columnName]=dataset[columnName].var()
        descriptive.loc["std",columnName]=dataset[columnName].std()
         
     return descriptive

In [54]:
Univariate(dataset)

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
mean,95.355866,2.797968,17.652147,1455.611019,65.636737,3.109333,3.386967,61.359527,111.492723,4436.418737,5.544421,368.239709,3.722107
median,105.0,2.8,17.652147,1455.611019,66.28,3.12,3.386967,61.359527,107.0,4436.418737,5.544421,368.239709,4.0
mode,105.0,2.797968,17.652147,1455.611019,85.0,2.86,3.386967,61.359527,111.492723,4436.418737,6.0,368.239709,5.0
Q1:25%,88.4,2.09,16.185,1439.6,55.845,2.78,2.975,48.205,68.0,2885.6,3.0,229.2,2.0
Q2:50%,105.0,2.8,17.652147,1455.611019,66.28,3.12,3.386967,61.359527,107.0,4436.418737,5.544421,368.239709,4.0
Q3:75%,105.0,3.495,19.27,1470.65,76.625,3.47,3.79,73.85,154.0,6116.05,8.0,512.35,5.0
99,105.0,5.003,22.9188,1509.97,85.0,4.2208,4.5402,100.0,261.06,7900.768,14.02,682.922,9.5
Q4:100%,130.425,5.66625,24.0725,1520.95,108.40375,4.5125,5.06,113.065,289.5,11271.85,15.5,964.05,9.5
IQR,16.6,1.405,3.085,31.05,20.78,0.69,0.815,25.645,86.0,3230.45,5.0,283.15,3.0
1.5RULE,24.9,2.1075,4.6275,46.575,31.17,1.035,1.2225,38.4675,129.0,4845.675,7.5,424.725,4.5
LESSER,63.5,-0.0175,11.5575,1393.025,24.675,1.745,1.7525,9.7375,-61.0,-1960.075,-4.5,-195.525,-2.5
GREATER,129.9,5.6025,23.8975,1517.225,107.795,4.505,5.0125,112.3175,283.0,10961.725,15.5,937.075,9.5
min,62.625,-0.08375,11.3725,1390.15,24.07375,1.7325,1.7,8.845,-66.5,-2285.35,-4.5,-217.95,-2.5
max,130.425,5.66625,24.0725,1520.95,108.40375,4.5125,5.06,113.065,289.5,11271.85,15.5,964.05,9.5
skew,-1.162171,-0.09754,-0.206404,0.194057,-0.275547,-0.157983,-0.05849,-0.078344,0.340416,-0.128951,0.359184,-0.102538,0.140254
kurtosis,0.115064,-0.29109,0.059386,-0.130254,-0.559784,-0.263503,-0.414133,-0.167706,-0.338575,-0.670438,-0.093162,-0.61968,-0.43123
var,187.806421,1.097511,5.793724,524.438487,168.047019,0.284746,0.328056,328.3994,3633.923142,4309962.81598,11.99758,31961.199893,5.307979
std,13.704248,1.047621,2.407016,22.900622,12.963295,0.533616,0.572762,18.121794,60.28203,2076.044994,3.463752,178.776956,2.303905

In [55]:
dataset

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults
0,94.56,1.84,20.15,1470.3,57.150000,2.91,3.09,70.42,83.000000,2889.6,5.0,224.3,3.0
1,105.00,4.27,20.10,1420.8,84.050000,3.83,4.28,49.96,192.000000,7276.7,13.0,602.8,7.0
2,67.60,1.64,19.80,1471.1,46.360000,2.23,2.96,80.75,31.000000,1082.3,1.0,101.4,1.0
3,105.00,4.24,13.63,1443.8,80.730000,3.33,3.75,29.09,111.492723,6716.5,12.0,575.6,9.0
4,92.52,2.13,18.64,1466.5,62.520000,3.11,3.06,56.64,105.000000,3116.7,4.0,281.1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,75.25,2.01,18.61,1488.1,44.030000,2.26,2.65,72.45,36.000000,1156.6,2.0,76.5,1.0
495,99.81,2.98,16.39,1456.0,54.790000,3.34,2.72,74.99,40.000000,2621.0,7.0,173.2,2.0
496,99.31,2.66,19.45,1443.8,65.636737,2.67,2.94,47.38,76.000000,3639.4,4.0,256.4,2.0
497,85.15,2.41,14.90,1470.0,56.170000,2.73,2.83,40.67,41.000000,2693.9,8.0,218.3,4.0
498,86.66,1.46,15.64,1479.8,58.780000,3.28,3.26,55.87,67.000000,2991.5,4.0,256.7,2.0

In [56]:
dataset.isnull().sum()

Motor_Temperature_C       0
Motor_Vibration_mm_s      0
Motor_Current_A           0
Motor_Speed_RPM           0
Brake_Temperature_C       0
Door_Opening_Time_s       0
Door_Closing_Time_s       0
Load_Percentage           0
Number_of_Trips           0
Operating_Hours           0
Error_Count               0
Days_Since_Maintenance    0
Previous_Faults           0
dtype: int64

In [57]:
dataset['Maintenance_Required']=output

In [58]:
dataset

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults,Maintenance_Required
0,94.56,1.84,20.15,1470.3,57.150000,2.91,3.09,70.42,83.000000,2889.6,5.0,224.3,3.0,0.0
1,105.00,4.27,20.10,1420.8,84.050000,3.83,4.28,49.96,192.000000,7276.7,13.0,602.8,7.0,1.0
2,67.60,1.64,19.80,1471.1,46.360000,2.23,2.96,80.75,31.000000,1082.3,1.0,101.4,1.0,0.0
3,105.00,4.24,13.63,1443.8,80.730000,3.33,3.75,29.09,111.492723,6716.5,12.0,575.6,9.0,1.0
4,92.52,2.13,18.64,1466.5,62.520000,3.11,3.06,56.64,105.000000,3116.7,4.0,281.1,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,75.25,2.01,18.61,1488.1,44.030000,2.26,2.65,72.45,36.000000,1156.6,2.0,76.5,1.0,0.0
495,99.81,2.98,16.39,1456.0,54.790000,3.34,2.72,74.99,40.000000,2621.0,7.0,173.2,2.0,0.0
496,99.31,2.66,19.45,1443.8,65.636737,2.67,2.94,47.38,76.000000,3639.4,4.0,256.4,2.0,0.0
497,85.15,2.41,14.90,1470.0,56.170000,2.73,2.83,40.67,41.000000,2693.9,8.0,218.3,4.0,0.0
498,86.66,1.46,15.64,1479.8,58.780000,3.28,3.26,55.87,67.000000,2991.5,4.0,256.7,2.0,0.0

# Null values were removed

In [59]:
dataset=dataset.dropna(subset=['Maintenance_Required'])

In [60]:
dataset.isnull().sum()

Motor_Temperature_C       0
Motor_Vibration_mm_s      0
Motor_Current_A           0
Motor_Speed_RPM           0
Brake_Temperature_C       0
Door_Opening_Time_s       0
Door_Closing_Time_s       0
Load_Percentage           0
Number_of_Trips           0
Operating_Hours           0
Error_Count               0
Days_Since_Maintenance    0
Previous_Faults           0
Maintenance_Required      0
dtype: int64

In [61]:
# Save the cleaned dataset
dataset.to_csv("Elevator_predictive_maintenance_cleaned.csv", index=False)

In [62]:
dataset

,Motor_Temperature_C,Motor_Vibration_mm_s,Motor_Current_A,Motor_Speed_RPM,Brake_Temperature_C,Door_Opening_Time_s,Door_Closing_Time_s,Load_Percentage,Number_of_Trips,Operating_Hours,Error_Count,Days_Since_Maintenance,Previous_Faults,Maintenance_Required
0,94.56,1.84,20.15,1470.3,57.150000,2.91,3.09,70.42,83.000000,2889.6,5.0,224.3,3.0,0.0
1,105.00,4.27,20.10,1420.8,84.050000,3.83,4.28,49.96,192.000000,7276.7,13.0,602.8,7.0,1.0
2,67.60,1.64,19.80,1471.1,46.360000,2.23,2.96,80.75,31.000000,1082.3,1.0,101.4,1.0,0.0
3,105.00,4.24,13.63,1443.8,80.730000,3.33,3.75,29.09,111.492723,6716.5,12.0,575.6,9.0,1.0
4,92.52,2.13,18.64,1466.5,62.520000,3.11,3.06,56.64,105.000000,3116.7,4.0,281.1,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,75.25,2.01,18.61,1488.1,44.030000,2.26,2.65,72.45,36.000000,1156.6,2.0,76.5,1.0,0.0
495,99.81,2.98,16.39,1456.0,54.790000,3.34,2.72,74.99,40.000000,2621.0,7.0,173.2,2.0,0.0
496,99.31,2.66,19.45,1443.8,65.636737,2.67,2.94,47.38,76.000000,3639.4,4.0,256.4,2.0,0.0
497,85.15,2.41,14.90,1470.0,56.170000,2.73,2.83,40.67,41.000000,2693.9,8.0,218.3,4.0,0.0
498,86.66,1.46,15.64,1479.8,58.780000,3.28,3.26,55.87,67.000000,2991.5,4.0,256.7,2.0,0.0